### ISSUE TITLE
Melhor issue da história!

### ISSUE THREAD

**Issue by JungerMarzPrototypeB** [victornjg/AulaGoApp#2]
A imagem docker já está pronta?
E não tinha um Trello? 

~~melhor issue da história~~

**Comment by victornjg** [comment]
Sim, já está. O link dela está dela é este [https://hub.docker.com/r/victornjg/ionic_environment/](url). Se o seu usuário do Trello for o rafaelmachado34, você já está adicionado no quadro. Ah e quando for usar o container instale uma versão das mais recentes do Node. Porque eu encontrei um problema ao usar a versão mais estável (6.4.0), um erro relacionado a um pacote chamado semver. Ai é só usar `nvm ls-remote` depois `nvm use {versao}`. Aqui a versão 8.5.0 tá funcionado perfeitamente.

**Comment by JungerMarzPrototypeB** [comment]
Ah, de boas então, uso o Node Chakra 9, então provavelmente nem vai dar problema.

Melhor tirar esse tal de rafaelmachado34 do Trello also haushuahsuhas
